export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';
export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
export const MARK_NOTIFICATION_READ_SUCCESS = "MARK_NOTIFICATION_READ_SUCCESS";
export const MARK_NOTIFICATION_READ_FAIL = "MARK_NOTIFICATION_READ_FAIL"; 

export const GET_ALERTS = 'GET_ALERTS';
export const GET_ALERTS_SUCCESS = 'GET_ALERTS_SUCCESS';
export const GET_ALERTS_FAIL = 'GET_ALERTS_FAIL'; 

export const MARK_ALERT_READ = 'MARK_ALERT_READ';
export const MARK_ALERT_READ_SUCCESS = 'MARK_ALERT_READ_SUCCESS';
export const MARK_ALERT_READ_FAIL = 'MARK_ALERT_READ_FAIL'; 

export const RECEIVE_NOTIFICATION_SSE = 'RECEIVE_NOTIFICATION_SSE'; 
export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT'; 