export const GET_REFERRALS = 'GET_REFERRALS';
export const GET_REFERRALS_SUCCESS = 'GET_REFERRALS_SUCCESS';
export const GET_REFERRALS_FAIL = 'GET_REFERRALS_FAIL';

export const UPDATE_REFERRAL_STATUS = 'UPDATE_REFERRAL_STATUS';
export const UPDATE_REFERRAL_STATUS_SUCCESS = 'UPDATE_REFERRAL_STATUS_SUCCESS';
export const UPDATE_REFERRAL_STATUS_FAIL = 'UPDATE_REFERRAL_STATUS_FAIL';

export const CLEAR_REFERRAL_STATUS_MESSAGES = 'CLEAR_REFERRAL_STATUS_MESSAGES';

export const GET_REFERRAL_AMOUNT = 'GET_REFERRAL_AMOUNT';
export const GET_REFERRAL_AMOUNT_SUCCESS = 'GET_REFERRAL_AMOUNT_SUCCESS';
export const GET_REFERRAL_AMOUNT_FAIL = 'GET_REFERRAL_AMOUNT_FAIL';

export const PAY_REFERRALS = 'PAY_REFERRALS';
export const PAY_REFERRALS_SUCCESS = 'PAY_REFERRALS_SUCCESS';
export const PAY_REFERRALS_FAIL = 'PAY_REFERRALS_FAIL'; 