// Generic Records Action Types
export const GET_SPECIALTIES = 'GET_SPECIALTIES';
export const GET_SPECIALTIES_SUCCESS = 'GET_SPECIALTIES_SUCCESS';
export const GET_SPECIALTIES_FAIL = 'GET_SPECIALTIES_FAIL';

export const GET_PRACTICES = 'GET_PRACTICES';
export const GET_PRACTICES_SUCCESS = 'GET_PRACTICES_SUCCESS';
export const GET_PRACTICES_FAIL = 'GET_PRACTICES_FAIL'; 