export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_MONITORED_PATIENTS = "GET_MONITORED_PATIENTS";
export const GET_MONITORED_PATIENTS_SUCCESS = "GET_MONITORED_PATIENTS_SUCCESS";
export const GET_NOT_MONITORED_PATIENTS = "GET_NOT_MONITORED_PATIENTS";
export const GET_NOT_MONITORED_PATIENTS_SUCCESS = "GET_NOT_MONITORED_PATIENTS_SUCCESS";
export const API_FAIL = "PATIENTS_API_FAIL";
export const ADD_PATIENT = "ADD_PATIENT";
export const ADD_PATIENT_SUCCESS = "ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_MESSAGE = "ADD_PATIENT_MESSAGE";
export const GET_RECENT_PATIENTS = "GET_RECENT_PATIENTS";
export const GET_RECENT_PATIENTS_SUCCESS = "GET_RECENT_PATIENTS_SUCCESS";
export const GET_PATIENT_DETAIL = "GET_PATIENT_DETAIL";
export const GET_PATIENT_DETAIL_SUCCESS = "GET_PATIENT_DETAIL_SUCCESS";
export const UPDATE_PATIENT_DETAIL = "UPDATE_PATIENT_DETAIL";
export const UPDATE_PATIENT_DETAIL_SUCCESS = "UPDATE_PATIENT_DETAIL_SUCCESS";
export const UPDATE_PATIENT_DETAIL_FAIL = "UPDATE_PATIENT_DETAIL_FAIL";
export const GET_CONSENT_FORMS = "GET_CONSENT_FORMS";
export const GET_CONSENT_FORMS_SUCCESS = "GET_CONSENT_FORMS_SUCCESS";
export const GET_CONSENT_FORMS_FAIL = "GET_CONSENT_FORMS_FAIL";

// 3D Plans
export const CREATE_3D_PLAN = "CREATE_3D_PLAN";
export const CREATE_3D_PLAN_SUCCESS = "CREATE_3D_PLAN_SUCCESS";
export const CREATE_3D_PLAN_FAIL = "CREATE_3D_PLAN_FAIL";
export const GET_3D_PLAN = "GET_3D_PLAN";
export const GET_3D_PLAN_SUCCESS = "GET_3D_PLAN_SUCCESS";
export const GET_3D_PLAN_FAIL = "GET_3D_PLAN_FAIL";
export const UPDATE_3D_PLAN = "UPDATE_3D_PLAN";
export const UPDATE_3D_PLAN_SUCCESS = "UPDATE_3D_PLAN_SUCCESS";
export const UPDATE_3D_PLAN_FAIL = "UPDATE_3D_PLAN_FAIL";
export const DELETE_3D_PLAN = "DELETE_3D_PLAN";
export const DELETE_3D_PLAN_SUCCESS = "DELETE_3D_PLAN_SUCCESS";
export const DELETE_3D_PLAN_FAIL = "DELETE_3D_PLAN_FAIL"; 

export const GET_TREATMENT_STEPS = "GET_TREATMENT_STEPS";
export const GET_TREATMENT_STEPS_SUCCESS = "GET_TREATMENT_STEPS_SUCCESS";
export const GET_TREATMENT_STEPS_FAIL = "GET_TREATMENT_STEPS_FAIL";

export const GET_SCAN_DETAIL = "GET_SCAN_DETAIL";
export const GET_SCAN_DETAIL_SUCCESS = "GET_SCAN_DETAIL_SUCCESS";
export const GET_SCAN_DETAIL_FAIL = "GET_SCAN_DETAIL_FAIL";

// Change aligner
export const CHANGE_ALIGNER = "CHANGE_ALIGNER";
export const CHANGE_ALIGNER_SUCCESS = "CHANGE_ALIGNER_SUCCESS";
export const CHANGE_ALIGNER_FAIL = "CHANGE_ALIGNER_FAIL";