export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
export const ADD_ORDER = "ADD_ORDER";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
export const ADD_ORDER_MESSAGE = "ADD_ORDER_MESSAGE";
export const CLEAR_ORDER_MESSAGES = "CLEAR_ORDER_MESSAGES"; 